######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 13 10:24:43 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += server.h
SOURCES += main.cpp server.cpp
QT += core gui network
