testqt:		testqt.cpp
	g++ -m64 -o testqt testqt.cpp `pkg-config --cflags --libs QtCore QtGui glib-2.0`
onemoretry:	onemoretry.cpp
	g++ -m64 -o onemoretry onemoretry.cpp `pkg-config --cflags --libs QtCore QtGui`
