######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 3 11:52:23 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += highlighter.h mainwindow.h
SOURCES += highlighter.cpp main.cpp mainwindow.cpp
