######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 13 17:32:27 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += server.h
SOURCES += server.cpp
QT += network
