######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 26 19:04:31 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.h ../common.h
SOURCES += client.cpp ../common.cpp
QT += network
