######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 13 17:30:28 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.h
SOURCES += client.cpp
