######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 13 10:21:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.h
SOURCES += client.cpp
QT += core gui network
